# Generated by Django 4.2.5 on 2023-09-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_lesson_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=5000, verbose_name='стоимость курса'),
        ),
    ]
